# Generated by Django 4.1.6 on 2023-03-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2d1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
